package sk.richardbobik.animestarterpack;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;

import java.util.ArrayList;

public class SettingsActivity extends AppCompatActivity {

    private Button btnDatabaseSetup;
    private ImageView btnSakura;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_settings);

        createArrayList();

        initViews();

        btnDatabaseSetup.setOnClickListener(new View.OnClickListener() {
            ArrayList<Show> arrayList = createArrayList();
            @Override
            public void onClick(View v) {
                AlertDialog.Builder alert = new AlertDialog.Builder(SettingsActivity.this);
                        alert.setTitle("List Creation/Reset")
                        .setMessage("If you have previously created the list of shows, this action will delete all your progress. Would you like to continue?")
                        .setPositiveButton("OK", (dialog, which) -> {
                            DatabaseConnector db = new DatabaseConnector(SettingsActivity.this);
                            db.deleteOne();
                            for (Show show : arrayList) {
                                setDB(show);
                            }
                        });
                        alert.setNegativeButton("No", (dialog, which) -> {
                            /**
                             * Closes the Alert Dialog. No extra action necessary.
                             */
                        });
                        alert.create().show();
            }
        });

        btnSakura.setOnClickListener(v -> {
            /**
             * On click event is intentionally empty.
             * Meant as a joke for Naruto fans.
             */
        });
    }

    @Override
    public void onBackPressed() {
        Intent intent = new Intent(SettingsActivity.this, MainActivity.class);
        startActivity(intent);
        super.onBackPressed();
    }

    private void initViews() {
        btnDatabaseSetup = findViewById(R.id.btnDatabaseSetup);
        btnSakura = findViewById(R.id.btnSakura);
    }

    public void setDB(Show show) {

        DatabaseConnector databaseConnector = new DatabaseConnector(SettingsActivity.this);
        databaseConnector.addOne(show);
    }

    public static ArrayList<Show> createArrayList() {

        ArrayList<Show> allShows = new ArrayList<>();
        allShows.add(new Show(0, "Nausicaä of the Valley of the Wind", "https://flxt.tmsimg.com/assets/p9311_p_v10_ab.jpg", "Post-apocalyptic / sci-fi movie that is suitable for all ages.", "Far in the distant future, humans are forced to live in small colonies spread around the planet. Most of the surface is covered by toxic wastelands occupied by a race of giant insects. People are surviving for generations by avoiding or killing the “intruders”. But there might be a better way. Nausicaä.", "posta", "notViewed"));
        allShows.add(new Show(1, "Blame", "https://images-na.ssl-images-amazon.com/images/I/91-aLkIi4bL._RI_.jpg", "Action filled post-apocalyptic thriller.", "Advanced human civilization is using machines to build and run enormous cities. Malfunction in software turns their mechanical servants against themselves. Key to reverse the dire situation lies in “Net Terminal Genes”, a specific genetic material that allows humans to access the control network. But is there still anyone with NTG left? ", "posta", "notViewed"));
        allShows.add(new Show (2, "Akira", "https://wallpaperaccess.com/full/38480.jpg", "Iconic cyberpunk dystopian anime.", "For Akira, the world in the year 2019 is harsh and unforgiving. Battles with rival biker gangs are everyday reality. Everything changes when the young gang leader, and his friends meet Takashi, product of a secret government project. Things will turn from bad to worse very quickly. ", "posta", "notViewed"));
        allShows.add(new Show (3, "Cowboy Bebop", "https://i.pinimg.com/736x/c1/ea/f2/c1eaf24f64dc71ea7ae0149f59be9a5c.jpg", "Space themed action anime made as an extra to a popular TV show. ", "When the huge bounty of 300 million woolong is issued for capturing the terrorist that released the new deadly pathogen on the surface of Mars, Bebop’s crew of bounty hunters is on its way to the red planet. After initial investigation the heroes start to realize that they might be dealing with something much bigger than just a lonely wolf. ", "posta","notViewed"));
        allShows.add(new Show (4, "Ghost In The Shell", "https://images-na.ssl-images-amazon.com/images/I/A1M+y+OBUSL._RI_.jpg", "Neo-noir action thriller with mature themes.", "Augmentation of the body with the cybernetic parts is common and humans can even access computer networks directly with their brain. This significant achievement also brought some problems. Now even humans themselves can be hacked. And when a machine can acquire its own “ghost” the whole perception of life will change. ", "posta", "notViewed"));
        allShows.add(new Show (5, "The End Of Evangelion", "https://i.pinimg.com/originals/fa/fe/2c/fafe2ce520f025a494b2a3b834fdba2c.jpg", "Psychological action movie aimed for mature audience.", "Probably the most iconic movie of its genre follows the attack of the UN forces on the Nerv facility. Evangelion pilots already shaken by previous hardships are forced to fight for their own lives. I would recommend watching the Neon Genesis Evangelion first as the movie directly follows the events in the TV series. ", "action",  "notViewed"));
        allShows.add(new Show (6, "Sword Of The Stranger", "https://flxt.tmsimg.com/assets/p183685_v_v10_aa.jpg", "Historical action drama based in feudal Japan.", "When the young boy Kotaro and his dog Tobimaru barely escape their unknown pursuers, they find a shelter in an abandoned temple. Here, by chance, the unfortunate duo meets Nanashi, a wandering ronin, and possibly the only chance of escaping the cruel faith. ", "action",  "notViewed"));
        allShows.add(new Show (7, "Ninja Clash in the Land of Snow", "https://flxt.tmsimg.com/assets/p169836_p_v10_ab.jpg", "Ninja themed action anime and the first of the Naruto movies.", "Naruto, Sasuke and Sakura are being sent to a bodyguard mission. The target is Yukie Fujikaze, a popular movie actress who is shooting her newest film. When ninjas find out that Yukie’s true identity is Koyuki Kazahana, princess from the Land of Snow, the true reason behind the kidnapping attempts might reveal itself as well. ", "action",  "notViewed"));
        allShows.add(new Show (8, "Strong World", "https://879ed873-madman-com-au.akamaized.net/media/Series/17950/17950-729832.jpg", "Action-adventure film based on One Piece manga series.", "The evil captain Shiki captures Nami in the attempt to conquer the East Blue with his pirate crew. “Straw Hat” Luffy and his friends will have to overcome many dangers to rescue Nami and thwart Shiki’s disturbing plans. ", "action",  "notViewed"));
        allShows.add(new Show (9, "Ordinal Scale", "https://m.media-amazon.com/images/M/MV5BZGE4M2M2OTYtZDgwMy00NGYwLWE0YTYtYzkyMDFjYWFhN2QzXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg", "High rated action movie from a popular Sword Art universe. ", "When Augma is released for the public, online players no longer need to use FullDive and can be conscious in real life while playing. Asuna convinces Kirito to play Ordinal Scale, the new hit combat-based game. Will the newest adventure finally be a smooth sail for the gamers?", "action",  "notViewed"));
        allShows.add(new Show (10, "Your Name", "https://i.pinimg.com/originals/06/38/bb/0638bbb607b5ad0051c4277feb68ea81.jpg", "Absolute masterpiece within the romantic anime genre.", "Mitsuha Miyamizu, a high school girl from a Japanese countryside, suddenly starts switching bodies with Taki Tachibana, a student boy from Tokyo. What both youngsters took as vivid dreams at first swiftly turns into something much more serious. Movie is full of various twists, and it might take a few viewings until you can fully appreciate it’s depth. ", "romantic",  "notViewed"));
        allShows.add(new Show (11, "Weathering With You", "https://m.media-amazon.com/images/M/MV5BY2YxZDBlODEtYTZjNC00MTI2LTlmZGItZDZhMzdjZmU4YmE2XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg", "One of the brilliant new generation romantic anime.", "When Hodaka Morishima runs away from his home, he tries to start a new life in Tokyo. After a difficult start his luck finally turns when he gets a job as an assistant in a small magazine publishing company. His life completely changes once again when he meets young girl, Hina Amano.  Hina turns out to be one of the legendary “Sunshine Girls” and has the ability to control the weather. But everything comes with a price.", "romantic",  "notViewed"));
        allShows.add(new Show (12, "5 Centimeters Per Second", "https://www.themoviedb.org/t/p/original/rm3WRVPSmYQNhdEM55ZqD26Cqsa.jpg", "Romantic drama anime from well-known CoMix Wave studio.", "Movie follows the story of Takaki Toono and Akari Shinohara. Thanks to similar interests and life circumstances, a strong friendship is formed. This soon grows into a young love. Unfortunately, soon they are forced to separate as their families tend to often move. Can their bond survive?", "romantic",  "notViewed"));
        allShows.add(new Show (13, "The Garden Of Words", "https://m.media-amazon.com/images/M/MV5BZDFlYTk5NTQtYTkxMC00NWIyLThiOTYtNjZjYTJhMWJhM2NiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg", "Shorter than average romantic anime movie, but still well worth watching. ", "The Garden of Words is with its plot a little bit bolder than previous movies in this section. Movie depicts an affection between a 15-year-old student and a 27-year-old teacher. Both tend to skip school on rainy days to enjoy the solitude. Until these two lonely souls meet one morning. ", "romantic",  "notViewed"));
        allShows.add(new Show (14, "The Girl Who Leapt Through Time", "https://flxt.tmsimg.com/assets/p8471376_p_v13_ab.jpg", "Romantic / sci-fi family friendly anime movie. ", "After a clumsy accident, 17-year-old Makoto gains an ability to move back in time. Teenager enjoys her newfound power and use it in every imaginable situation. Soon she finds out that trying to fix one mistake might create many others and that even this incredible advantage has its limitations.", "romantic",  "notViewed"));
        allShows.add(new Show (15, "My Neighbor Totoro", "https://static.wikia.nocookie.net/dubbing9585/images/7/77/Totoroposter.jpg/revision/latest?cb=20171128165200", "My Neighbour Totoro is one in the long list of high rated movies from famous Ghibli studio. ", "University professor moves to the countryside with his two daughters to be close to his wife who is recovering from a long-term illness in a nearby hospital. A difficult life situation is for kids eased after they befriend a fluffy forest spirit named Totoro. ", "family",  "notViewed"));
        allShows.add(new Show (16, "Mewtwo Strikes Back", "https://m.media-amazon.com/images/M/MV5BN2NkZjA0OWUtZDgyMy00MjIxLWJhZTEtYjdmYzVjZTQ3YWRiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_.jpg", "First of the long series of Pokémon movies.", "Although the Pokémon movies often struggle with the ratings from the western critics, they are an inseparable part of the anime genre. Mewtwo Strikes Back offers an entertaining storyline for the younger viewers and it’s not afraid to poke into some “sensitive” topics to make even the older viewers think. ", "family",  "notViewed"));
        allShows.add(new Show (17, "Spirited Away", "https://i.pinimg.com/originals/bc/f3/c8/bcf3c8296368ae57d32d6747c05615b5.jpg", "Ghibli studio's jewel. Often considered to be one of the best movies of 21st century. ", "10-year-old Chihiro accidentally crosses the border between the real world and Kami, the world of spirits. To get back and help her parents that got transformed into pigs, she needs to overcome various obstacles and encounter probably the most colourful variety of characters in cinematic history. ", "family",  "notViewed"));
        allShows.add(new Show (18, "A Whisker Away", "https://mfiles.alphacoders.com/873/873996.png", "One of the newest additions to the top-rated anime movies.", "Problems at home and unanswered affection from the boy she likes makes Miyo Sasaki a troubled soul. When she receives a magical Noh mask from a mysterious mask seller, Miyo can suddenly transform into a cat at any time she wants. Although this seems like an answer to all the issues, a young girl soon finds out that being a cat can get pretty complicated. ", "family",  "notViewed"));
        allShows.add(new Show (19, "Arrietty", "https://m.media-amazon.com/images/M/MV5BZDY3ZGI0ZDAtMThlNy00MzAxLTg4YjAtNjkwYTkxNmQ4MjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg", "Family fantasy anime based on European folklore.", "“Borrowers” used to be common in every well organised household. But this is not the case anymore. There are only a few of them left in this world and they must be careful to stay safe from the humans. That’s why when Shoo discovers their presence, Arrietty and her family will have to face a difficult decision. ", "family",  "notViewed"));
        allShows.add(new Show (20, "Grave Of The Fireflies", "https://flxt.tmsimg.com/assets/p158931_p_v10_aa.jpg", "Anime tragedy drama from the time of a second world war. ", "Grave of the Fireflies can be a difficult movie to handle for those with a softer nature. Film depicts a story of two orphans struggling to survive in an unforgiving environment during the second world war. Help from other people is limited due to the circumstances and they will have to rely just on each other. ", "drama",  "notViewed"));
        allShows.add(new Show (21, "Eternity and the Auto Memory Doll", "https://m.media-amazon.com/images/M/MV5BZjljM2M1ZTgtZGM4My00OGRkLTliMjAtYzJiZDBkMzQ5ZDkzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg", "Anime drama from alternate reality. ", "Violet Evergarden, a former soldier injured during the war, is hired to tutor a young lady from a rich family. After a bumpy start, her student finally opens to her, and a strong friendship is formed. But there is still something very important missing for Violet.", "drama",  "notViewed"));
        allShows.add(new Show (22, "Whisper of the Heart", "https://m.media-amazon.com/images/I/71lV0sXVfAL._AC_SY879_.jpg", "Feel good anime drama excelling in both animation and music. ", "Junior High School girl Shizuku loves reading books and decides to rewrite the lyrics for her favourite song as a project for the school graduation. When a boy named Seiji finds the lyrics by accident, he first teases Shizuku for the mockery version of the song but soon starts to admire her talent. ", "drama",  "notViewed"));
        allShows.add(new Show (23, "A Silent Voice", "https://www.reelviews.net/resources/img/posters/thumbs/silent_voice_poster.jpg", "Psychological drama that points at dangers of bullying at schools. ", "When Shoko Nishimiya, deaf transfer student, joins the sixth-grade class, she is being mercilessly bullied by a boy named Shoya. Shoko is soon forced to leave the school.  Years later Shoya can no longer bear the guilt of his miss-doings and decides to end his life. He changes his mind at the last minute and tries to right his wrongs instead. ", "drama",  "notViewed"));
        allShows.add(new Show (24, "When Marnie Was There", "https://img.24reel.com/cdn/big/movie/3cc60c07-0704-4371-808f-48a0d4c199c9.jpg", "Feel good anime drama with fantasy attributes.", "When Marnie Was There explores the relationship between 12-year-old girl Anna and her foster parents. After an asthma attack, Anna is sent to the countryside to spend a vacation with the relatives of her foster mum. Here Anna meets a very unlikely friend, a blond girl named Marnie. ", "drama",  "notViewed"));
        allShows.add(new Show (25, "Naruto", "https://blogclan.katecary.co.uk/wp-content/uploads/2021/01/MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg", "A legendary ninja themed anime series. ", "Series is focused on the transformation of 3 young students, Naruto Uzumaki, Sasuke Uchiha and Sakura Haruno, into professional ninjas. With the help of their sensei Kakashi Hatake and many other friends the journey becomes entertaining and a real fun to watch. ", "actions",  "notViewed"));
        allShows.add(new Show (26, "Neon Genesis Evangelion", "https://picfiles.alphacoders.com/431/thumb-431953.jpg", "Absolute must watch anime series.", "After a mysterious asteroid impact in Antarctica, strange creatures of enormous proportions start to attack the world. Young generation of pilots able to control the giant Mechs, the Evangelions, might be humanity's only hope for survival.", "actions",  "notViewed"));
        allShows.add(new Show (27, "Tokyo Ghoul", "https://i.pinimg.com/originals/94/95/9f/94959f0b0ae8e4f3c9efb2207154bbc7.jpg", "Dark action / fantasy anime. ", "In the alternate universe, organisms named ghouls live among ordinary people. Ghouls possess many extraordinary powers and need to feed on humans to survive. Series follows story of Ken Kaneki who became a half-ghoul after being attacked by one of the blood thirsty creatures. Ken decides to help the government with the fight against his own kind. ", "actions",  "notViewed"));
        allShows.add(new Show (28, "Attack On Titan", "https://i.pinimg.com/originals/c4/cb/57/c4cb5734c7c94d3413efdaa3bca09a6d.jpg", "Long running dark TV series based on the Attack on Titan manga. ", "After humanity faced near extinction by giant humanoids named Titans, they managed to survive only in one last location protected by concentric walls. When Eren’s mother is killed in a surprising Titan attack, the boy joins the military and swears revenge on the enemy. ", "actions",  "notViewed"));
        allShows.add(new Show (29, "Fullmetal Alchemist", "https://www.themoviedb.org/t/p/w500/v9mndUyub3Ib5md42bk2C53jRV0.jpg", "Action / fantasy anime TV series.", "Series follows the story of brothers Edward and Alphonse Elric and their search for the Philosopher’s Stone. Stone has an extraordinary power to prolong the owner’s life. But this ability might come with too high of a price to pay. ", "actions",  "notViewed"));
        allShows.add(new Show (30, "Gurren Lagann", "https://res.cloudinary.com/jerrick/image/upload/v1614567421/603c57fd1d0ec2001c8ed372.jpg", "Mech themed sci-fi anime. ", "In the alternate future, the human race is ruled by the Spiral King, Lordgenome. People are forced to live in small communities underground and have no connection to other subterranean dwellings or the surface world. One day, the main character, Simon, finds a weird shaped key.  Simon uses the key to activate the mech called Gunman and with its help deflects the attack on his village. Thanks to the Gunman, he is also able to reach the surface. ", "scifis",  "notViewed"));
        allShows.add(new Show (31, "Kiznaiver", "https://i.pinimg.com/originals/88/8e/7a/888e7adee1bf00f966141212599578ca.jpg", "Sci-fi anime that is not a part of the mainstream. ", "Group of teenagers are kidnapped and forced to join the Kizuna System. Every member of the program is connected to other ones and shares all their pain. What amount of evil is acceptable for the greater good? Kuznavier. ", "scifis",  "notViewed"));
        allShows.add(new Show (32, "From the New World", "https://1.bp.blogspot.com/-zuLvkIbAUak/XNgkXRPyyMI/AAAAAAAAAZc/2ORaU_JGiwkNO6ouxvBoPGtc8WOxT87ZACLcBGAs/s1600/Shin_Sekai_Yori_Cover.jpg", "Anime based on a popular Japanese novel. ", "It's the year 3013 and evolution allowed a small number of the human population to develop psychic abilities called “Canto”. Even these small numbers manage to destroy modern society and the new world needs to be formed.  ", "scifis",  "notViewed"));
        allShows.add(new Show (33, "School-Live!", "https://i.ebayimg.com/images/g/YBgAAOSwP2ZeYe6s/s-l1600.jpg", "A charming sci-fi / post-apocalyptic anime that makes you sad and happy at the same time.", "Show follows a story of a few students that managed to survive a zombie apocalypse and chose their school as a base camp. One of the main characters, Yuki, suffered from a mental breakdown due to recent events and still perceives the world as it once was. What sounds as a disadvantage, is actually helping her friends to make the best out of the bad situation. ", "scifis",  "notViewed"));
        allShows.add(new Show (34, "Parasyte", "https://i.pinimg.com/originals/5e/3b/e1/5e3be1e0672a36559d577e785914defd.jpg", "Horror / sci-fi anime series. ", "When a tiny wormish aliens called Parasites arrive on earth, they quickly start gaining control over humans by infesting their brains. One of the Parasites also tries to take over the main character Shinichi. Alien fails and instead of the brain, he ends up in Shinichi’s arm. This creates an unusual situation when both parasite and the host still keep their consciousness. ", "scifis",  "notViewed"));
        allShows.add(new Show (35, "The Seven Deadly Sins", "https://knowitinfo.com/wp-content/uploads/2020/12/the-seven-deadly-sins-5517.jpg", "Fantasy / comedy anime series. ", "Story begins 10 years after a group of knights known as “Seven Deadly Sins” has been disbanded for plotting to take over the kingdom. Princess Elizabeth starts her adventure by looking for these powerful warriors as she is trying to save the Liones from the order of Holy Knights, it’s former protectors. ", "fantasys",  "notViewed"));
        allShows.add(new Show (36, "Demon Slayer", "https://m.media-amazon.com/images/I/61Zm2hsRJ0L._AC_SL1024_.jpg", "Interesting storyline and great animations made the Demon Slayer one of the most popular anime series ever made. ", "Main character Tanjiro comes home from a nearby town only to find out that his family have been slain and his younger sister Nezuko turned into a demon. In the forest, he meets a demon slayer that came too late to prevent the attack. Tanjiro stops the stranger from killing his sister and goes on a path to become a demon slayer himself. ", "fantasys",  "notViewed"));
        allShows.add(new Show (37, "Little Witch Academia", "https://wallpaperhook.com/wp-content/uploads/2020/11/4k-Little-Witch-Academia-Wallpaper-From-WallpaperHook.com-For-Free.jpg", "Magical fantasy anime series. ", "Show depicts the life of young students that started their studies at Luna Nova Magical Academy. Main protagonist Akko is a witch without any magical background. At first, Akko is not sure how she will cope with her life choice. But things might get easier after she discovers a wand that belonged to a powerful witch. ", "fantasys",  "notViewed"));
        allShows.add(new Show (38, "Castlevania", "https://i.imgur.com/avFxkxA.jpg", "High rated fantasy series based on the popular game. ", "After the bishop discovers scientific equipment in the house of a young woman named Lisa, he accuses her of witchcraft and orders to burn her at the stake. Lisa’s husband Dracula is devastated and declares that every last human in Wallachia will pay with his life for the bishop’s crime. Only man that can stop him is Trevor, a lonesome monster hunter. But he will need all the help that he can get.", "fantasys",  "notViewed"));
        allShows.add(new Show (39, "Miss Kobayashi's Dragon Maid", "https://m.media-amazon.com/images/M/MV5BNmIyNjMwZmEtOGE0Yy00ZGNmLWE3MmQtYmFkNDk0NGVjZjhkXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg", "A charming fantasy comedy series. ", "During the drunken walk through the forest, programmer Kobayashi encounters a “homeless” dragon. Encouraged by booze and feeling sorry for the creature, Kobayashi invites the dragon to stay at her home. The next morning, the dragon was already waiting at her door. Creature transforms into a human girl, Tohru and decides to repay its debt with maid work. ", "fantasys",  "notViewed"));
        allShows.add(new Show (40, "Higehiro", "https://static.netnaija.com/i/mr9KYzJL7q6.jpg", "Comedy drama that is aiming for a more mature audience. ", "After Yoshida gets rejected by his co-worker and long-time crush Airi, he decides to get drunk to ease the pain. In the middle of the night on his way home, Yoshida noticed teenage girl Sayu sitting alone under the streetlight. He allows Sayu to spend the night as she has nowhere else to go. And the complicated adventure is ready to set off. ", "dramas",  "notViewed"));
        allShows.add(new Show (41, "Nana", "https://picfiles.alphacoders.com/366/thumb-366156.jpg", "Anime drama series based on popular manga. ", "Series is named after the names of both main characters. Nana Komatsu is a small-town girl that hasn't yet learned how to take care of herself and Nana Oosaki is a lead singer in the popular band. Two girls first meet on the train, and once they see each other again checking out the same apartment in Tokyo, they decide to be roommates. ", "dramas",  "notViewed"));
        allShows.add(new Show (42, "Clannad", "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/Clannad_game_cover.jpg/220px-Clannad_game_cover.jpg", "Comedy drama series based on computer game. ", "Main character Tomoya claims not to care about anything in his life and likes to skip school to prove his point. One day he meets an odd girl named Nagisa who wishes to be his friend. At first, he just ignores the request. After seeing Nagisa a few more times, Tomoya decides to help her and her friends to revive the school’s drama club. ", "dramas",  "notViewed"));
        allShows.add(new Show (43, "Anohana", "https://img.wattpad.com/cover/33110877-288-k227948.jpg", "Emotional drama about loss and friendship. ", "When young girl Meiko Honma (Menma) dies in a tragic accident, a group of her friends slowly drift apart. Five years later Menma appears as a ghost to Jinta, former leader of the group and asks him to grant her a wish so she can pass to the afterlife. The problem is that Menma can’t remember her wish. ", "dramas",  "notViewed"));
        allShows.add(new Show (44, "Tokyo Magnitude 8.0", "https://img.betaseries.com/lwmWhgPPu5qAoRicL4NmF0WNgt4=/600x900/smart/https%3A%2F%2Fpictures.betaseries.com%2Ffonds%2Fposter%2F7687daa6f080683e192be49da9e6157c.jpg", "Anime disaster drama about the dangers of the earthquake. ", "Strong earthquake hits Tokyo when Mirai is visiting a robotic exposition with her younger brother Yuuki.  Siblings now must journey through the destroyed city to reunite with their family. On their way youngsters meet a single mother Mari who decides to help them. ", "dramas",  "notViewed"));
        allShows.add(new Show (45, "Toradora!", "https://picfiles.alphacoders.com/376/thumb-376792.jpg", "9 hours of pure entertainment that will make you, like many others, “google” the phrase “Toradora! 2”.", "Soft hearted Ryuji Takasu with the unwanted appearance of the intimidating criminal forms an unlikely alliance with a fierce but tiny Taiga Aisaka. Often bokken swinging “Palmtop Tiger” (Aisaka) finds out that they are both having difficulty confessing feelings to their crushes and forms a plan to help each other. ", "romantics",  "notViewed"));
        allShows.add(new Show (46, "Your Lie In April", "https://occ-0-300-299.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABWErHYI80kXKXNhyI72_BB-XZraL15LXuvb6txwy_l9QvERaLIqU6piOxMcl3zLGnKPfpUgKl3_-vvSwfJkto-0eCOz1HNDBig.jpg", "Romantic anime from the world of classical music. ", "When young talented musician Koosei Arima suddenly loses his mother, he suffers a mental breakdown. He is no longer able to hear the notes while playing and quits performing.  Things turn around for Arima when he meets an energetic violinist Kaori that is determined to bring him back to the music world. ", "romantics",  "notViewed"));
        allShows.add(new Show (47, "Love, Chunibyo & Other Delusions", "https://879ed873-madman-com-au.akamaized.net/media/Series/17289/17289-1055861.jpg", "Charming romantic anime series full of humorous situations. ", "Yuuta Togashi, a former “Chunibyo” (believe that one posse’s supernatural powers), is embarrassed about his past behaviour and tends to start a new school year as an ordinary student. This intent proves to be rather difficult after a current Chunibyo, a girl named Rikka, discovers his past and becomes interested in Yuuta.", "romantics",  "notViewed"));
        allShows.add(new Show (48, "Monthly Girls' Nozaki-kun", "https://cdn.myanimelist.net/images/anime/5/66083.jpg", "Romantic comedy series full of misunderstandings and colourful characters. ", "Main character Chiyo Sakura finally decides to confess her feelings to her crush, Umetarou Nozaki. Instead of an answer, Chiyo receives an autograph as Umetarou misunderstands her intention. It turns out that Nozaki-kun is also a respected manga artist and Chiyo ends up helping him with his work. ", "romantics",  "notViewed"));
        allShows.add(new Show (49, "A Lull In The Sea", "https://i.pinimg.com/474x/52/70/46/5270468a254268bcc7e006ffcba8c79e.jpg", "Anime series about overcoming the differences. ", "At first, all people used to live under the sea. When some of them decided to move to the surface, they slowly started to lose their “Ena”, protection lair granted by the sea-god to allow humans to breathe underwater. When 4 students from the underwater village are forced to attend the school on land, they will soon find out how far apart the two human species have drifted. ", "romantics",  "notViewed"));
        return allShows;
    }

}